VSPs: Add `BlockHeight` & `NetworkProportion`.
decred/dcrwebapi pull request #167
Opened 2022-09-09 18:35 UTC by amass01

This commit adds two new optional fields to the `c=vsp` command:

1. `BlockHeight`.
2. `NetworkProportion`.

2022-09-20 11:15 UTC, jholdstock requested changes

2022-09-20 11:15 UTC, jholdstock commented on service.go
> +	networkproportion, hasNetworkProportion := info["networkproportion"]
Needs to be `"estimatednetworkproportion"`

2022-09-20 11:15 UTC, jholdstock commented on service.go
> +	NetworkProportion uint32  `json:"networkproportion"`
VSPs return a float, not an int. See an example here: https://vspd.decredbrasil.com/api/v3/vspinfo

2022-09-20 11:15 UTC, jholdstock commented on service.go
> +	if hasBlockHeight {
Go ahead and make these two fields required, no need for optional. All VSPs should be on the latest vspd version by now

2022-09-20 11:15 UTC, jholdstock commented on service.go
> +	NetworkProportion uint32  `json:"networkproportion"`
Also make this `estimatednetworkproportion` please

2022-09-20 11:16 UTC, jholdstock commented
Please update your PR description to include "Closes #142"

2022-09-20 12:09 UTC, amass01 commented on service.go
> +	if hasBlockHeight {
awesome, will do

2022-09-20 14:06 UTC, jholdstock requested changes

2022-09-20 14:06 UTC, jholdstock commented on main.go
> +	defaultPort = ":8089"
Looks like you commited this by mistake

2022-09-20 14:06 UTC, jholdstock commented on service.go
> +	// APIVersionsSupported contains the collection of collections of API
```suggestion
	// APIVersionsSupported contains the collection of API
```

2022-09-21 07:03 UTC, jholdstock approved these changes
Looks good!

2022-09-21 07:04 UTC, merged